### ISSUE TITLE
Ensure submission meets Libero compliance checklist

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer-submission#7]
- [x] Ensure the README.md is reflective of the project.
- [x] Ensure the package is licensed under MIT (check the LICENCE file and package.json)
- [x] Add a code of conduct
- [x] Add the contributing document.
